package(default_visibility = ["//visibility:public"])

cc_test(
    name = "test_some_lib",
    srcs = ["test_some_lib.cpp"],
    deps = [
        "//lib",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)
