package(default_visibility = ["//visibility:public"])

cc_library(
    name = "lib",
    srcs = glob([
        "*.c",
        "*.cpp",
    ]),
    hdrs = glob([
        "*.h",
        "*.hpp",
    ]),
    deps = ["//raspPico:fake"],
)
